name: bnn_inference
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install flake8 pytest pytest-cov nvidia-pyindex
        python -m pip install -r requirements.txt
        python -m pip install -e .
    - name: Run Flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --ignore=W503,C901 --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests
      run: |
        python -m pytest
    - name: Generate coverage report
      run: |
        python -m pytest  --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      if: github.event_name != 'pull_request'
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        fail_ci_if_error: false
        verbose: true