# This workflow will install Python dependencies. Linter is triggered with different conditions in another workflow
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Python 3.10 release

on:
  push:
    tags:
    - 'release*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f environment/requirements.txt ]; then pip install -r environment/requirements.txt; fi
    - name: Install module
      run: |
        python setup.py install
    - name: Call training module
      run:
        bnn_train --help
    - name: Call prediction module
      run:
        bnn_predict --help
